/**
 * Loads the Material Symbols (Outlined) font.
 *
 * In dev (`vite`), this loads the FULL, unsubset font straight from
 * node_modules -- every one of its ~3,600 glyphs is available immediately,
 * no build step required, so any name used anywhere during development just
 * works. That font is roughly 3.5MB.
 *
 * In a production build, this instead loads the subset generated by
 * `npm run build`'s first step (scripts/build-icon-font.mjs), which
 * contains only the glyphs scripts/icon-names.mjs found referenced in src/
 * (roughly 10KB for the 23 this app currently uses -- see the material
 * symbols report for the measured before/after).
 *
 * The two imports are dynamic and guarded by `import.meta.env.DEV`, a
 * build-time constant Vite inlines and then dead-code-eliminates the other
 * branch of, so the production bundle never contains the 3.5MB font: only
 * whichever branch's import actually runs ships.
 */
if (import.meta.env.DEV) {
  import('material-symbols/outlined.css')
} else {
  import('./generated/icon-font-subset.css')
}
