"""ssh_verified_at on host_credentials

Revision ID: 01f962e7a491
Revises: 6cf6a0722d23
Create Date: 2026-08-06 16:08:28.627897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f962e7a491'
down_revision: Union[str, Sequence[str], None] = '6cf6a0722d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_credentials', sa.Column('ssh_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_credentials', 'ssh_verified_at')
    # ### end Alembic commands ###
