"""cert on entitlement_cache

Revision ID: bef9d92f4830
Revises: 01f962e7a491
Create Date: 2026-08-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef9d92f4830'
down_revision: Union[str, Sequence[str], None] = '01f962e7a491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlement_cache', sa.Column('cert', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlement_cache', 'cert')
    # ### end Alembic commands ###
